### ISSUE TITLE
[Arranger Server] - Development Environment Setup

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/composer#22]
## Summary 

Using this thread to track issues as I troubleshoot through the maestro development environment setup

All details and solutions will be outlined in the comments below

## Setup Steps

These will be updated as we solve common issues along the way

1. Clone the arranger repo:

```bash
git clone https://github.com/overture-stack/arranger.git
cd arranger
```

2. From the root directory run 

```
npm ci
```

**Comment by MitchellShiell** [comment]
# npm ci error 

Unable to install dependencies, this has been tested with various node versions, error log below:

```
arranger on  develop is 📦 3.0.0-beta.33 via ⬢ v21.6.2 on 🐳 v27.0.3 took 2.8s 
➜ npm ci        
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Binary found at /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/vendor/darwin-arm64-120/binding.node
npm ERR! Testing binary
npm ERR! Binary has a problem: Error: dlopen(/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/vendor/darwin-arm64-120/binding.node, 0x0001): tried: '/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/vendor/darwin-arm64-120/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/vendor/darwin-arm64-120/binding.node' (no such file), '/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/vendor/darwin-arm64-120/binding.node' (not a mach-o file)
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1475:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1212:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1028:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1237:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at module.exports (/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/lib/binding.js:19:10)
npm ERR!     at Object.<anonymous> (/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/lib/index.js:13:35)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1378:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1212:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR! Building the binary locally
npm ERR! Building: /Users/mshiell/.nvm/versions/node/v21.6.2/bin/node /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/mshiell/.nvm/versions/node/v21.6.2/bin/node',
npm ERR! gyp verb cli   '/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@21.6.2 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
npm ERR! gyp verb find Python - executing "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.12.2"
npm ERR! gyp info find Python using Python version 3.12.2 found at "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 21.6.2
npm ERR! gyp verb command install [ '21.6.2' ]
npm ERR! gyp verb install input version string "21.6.2"
npm ERR! gyp verb install installing version: 21.6.2
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 21.6.2
npm ERR! gyp verb build dir attempting to create "build" dir: /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mshiell/Library/Caches/node-gyp/21.6.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mshiell/Library/Caches/node-gyp/21.6.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mshiell/Library/Caches/node-gyp/21.6.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 23.6.0
npm ERR! gyp ERR! command "/Users/mshiell/.nvm/versions/node/v21.6.2/bin/node" "/Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/mshiell/Desktop/Conductor/conductor/composer/arranger/node_modules/node-sass
npm ERR! gyp ERR! node -v v21.6.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: /Users/mshiell/.npm/_logs/2024-10-01T16_38_30_432Z-debug-0.log
```



> [!NOTE]  
> Ciaran noted this in a likely [related issue here](https://github.com/overture-stack/arranger/issues/894) and outlined below
>
> https://www.npmjs.com/package/node-sass
>
> node-sass is deprecated and causes headaches from it's executable while running npm i with latest node LTS versions
>
> we should upgrade to sass as is officially recommended

**Comment by justincorrigible** [comment]
Issue identified: Python version dependency for node-gyp, as described here: https://github.com/nodejs/node-gyp?tab=readme-ov-file#installation
